### ISSUE TITLE
script has an major issue

### ISSUE THREAD

**Issue by Merith-TK** [coderobe/archlinux-steamlink#2]
instead of using `/tmp/archlinux-steamlink` it makes `/tmp/archlinux-steamlink?` which for some reason, cant be opened

**Comment by coderobe** [comment]
No it doesn't, this is handled by https://github.com/coderobe/archlinux-steamlink/blob/f426a794ea78c40eea984e06b7eb332b4f65d870/metadata/factory_test#L7

How are you running this?

**Comment by Merith-TK** [comment]
Well, I had it like a normal uefi partition setup. 1gb for the steam link
folder, and the rest for arch...

On phone via email, you can close this as when I went 1 partition it
suddenly started working....

**Comment by coderobe** [comment]
fwiw, I have also managed to build an upstream kernel for the steam link, and locally replaced the handoff with a kexec, which makes this much less janky than it is right now - i'll probably push an update to the repo "soon"

**Comment by Merith-TK** [comment]
Ohhhh! Nice, if you could add it to the air that would be great so it
updates!

Also alternative method for installing,
Archlinux on a Raspberry Pi or other armv7 system can bootstrap an arch
install, (instead of download the tar.gz)
